import React from 'react';
import SportsTennisIcon from '@mui/icons-material/SportsTennis';
import DirectionsRunIcon from '@mui/icons-material/DirectionsRun';
import FitbitIcon from '@mui/icons-material/Fitbit';
import PoolIcon from '@mui/icons-material/Pool';
import ShieldIcon from '@mui/icons-material/Shield';

export const pages = [
    { href: "/facilities", label: "Facilities", icon: <SportsTennisIcon /> },
    { href: "/programmes", label: "Programmes", icon: <DirectionsRunIcon /> },
    { href: "/home", label: "Home", icon: <FitbitIcon /> },
    { href: "/buypass", label: "Buy Pass", icon: <PoolIcon /> },
    { href: "/gameon", label: "Game On", icon: <ShieldIcon /> },
];

export const sportsIdList = {
    1: 'Badminton',
    2: 'Basketball',
    3: 'Floorball',
    4: 'Flying Disc',
    5: 'Futsal',
    6: 'Gateball',
    7: 'Gym',
    8: 'Hockey',
    9: 'Hockey (Night)',
    10: 'Lawn Bowl',
    11: 'Netball',
    12: 'Open Air Fitness Corner',
    13: 'Organised Programme',
    14: 'Outdoor',
    15: 'Petanque',
    16: 'Pickleball',
    17: 'Rugby',
    18: 'Sepak Takraw',
    19: 'Soccer',
    20: 'Soccer (Night)',
    21: 'Squash',
    22: 'Street Soccer',
    23: 'Swim',
    24: 'Table Tennis',
    25: 'Tennis',
    26: 'Tennis Wall',
    27: 'Volleyball'
};

export const sportsList = [
    'Badminton',
    'Basketball',
    'Floorball',
    'Flying Disc',
    'Futsal',
    'Gateball',
    'Gym',
    'Hockey',
    'Hockey (Night)',
    'Lawn Bowl',
    'Netball',
    'Open Air Fitness Corner',
    'Organised Programme',
    'Outdoor',
    'Petanque',
    'Pickleball',
    'Rugby',
    'Sepak Takraw',
    'Soccer',
    'Soccer (Night)',
    'Squash',
    'Street Soccer',
    'Swim',
    'Table Tennis',
    'Tennis',
    'Tennis Wall',
    'Volleyball'
];

export const venueList = [
    'ActiveSG Gym at Ang Mo Kio CC',
    'ActiveSG Gym at Fernvale Square',
    'ActiveSG Gym at Toa Payoh West CC',
    'ActiveSG Hockey Village Gym @ Boon Lay',
    'Admiralty Primary School Hall',
    'Anderson Secondary School Field',
    'Anderson Secondary School Hall',
    'Ang Mo Kio Primary School Hall',
    'Ang Mo Kio Secondary School Field',
    'Ang Mo Kio Secondary School Hall',
    'Ang Mo Kio Swimming Complex',
    'Bartley Secondary School Field',
    'Bartley Secondary School Hall',
    'Beacon Primary School Hall',
    'Beatty Secondary School Field',
    'Beatty Secondary School Hall',
    'Bedok Green Primary School Hall',
    'Bedok Green Secondary School Field',
    'Bedok Green Secondary School Hall',
    'Bedok South Secondary School Field',
    'Bedok South Secondary School Hall',
    'Bedok Stadium - Outside North Gate',
    'Bedok Stadium Gallery',
    'Bedok View Secondary School Field',
    'Bendemeer Primary School Hall',
    'Bendemeer Secondary School Field',
    'Bendemeer Secondary School Hall',
    'Bishan - Stadium Foyer',
    'Bishan ActiveSG Gym',
    'Bishan Sports Hall',
    'Bishan Swimming Complex',
    'Boon Lay Secondary School Field',
    'Bowen Secondary School Field',
    'Bowen Secondary School Hall',
    'Bukit Batok ActiveSG Gym',
    'Bukit Batok Swimming Complex',
    'Bukit Gombak - Level 1  Outdoor Courtyard',
    'Bukit Gombak ActiveSG Gym',
    'Bukit Gombak Sports Hall',
    'Bukit Panjang Govt High School Field',
    'Bukit Panjang Govt High School Hall',
    'Bukit Panjang Primary School Hall',
    'Bukit View Secondary School Field',
    'Bukit View Secondary School Hall',
    'Burghley Squash Centre',
    'Burghley Tennis Centre',
    'Canberra Primary School Hall',
    'Canberra Secondary School Field',
    'Canberra Secondary School Hall',
    'Cantonment Primary School Hall',
    'Casuarina Primary School Hall',
    'Cedar Primary School Hall',
    'Changkat Changi Secondary School Hall',
    'Changkat Primary School Hall',
    'CHIJ St Theresa Convent School Hall',
    'Choa Chu Kang ActiveSG Gym Level 3 (Free weights)',
    'Choa Chu Kang ActiveSG Gym Level 4 (Stack weights)',
    'Choa Chu Kang Conference Room',
    'Choa Chu Kang Secondary School Field',
    'Choa Chu Kang Swimming Complex',
    'Choa Chu Kang Tennis Centre',
    'Clementi - Sports Hall Foyer (Blue Multi-purpose Court)',
    'Clementi - Swimming Pool Foyer',
    'Clementi ActiveSG Gym',
    'Clementi Primary School Hall',
    'Clementi Sports Hall',
    'Clementi Swimming Complex',
    'Clementi Town Secondary School Field',
    'Clementi Town Secondary School Hall',
    'Commonwealth Secondary School Field',
    'Commonwealth Secondary School Hall',
    'Compassvale Primary School Hall',
    'Compassvale Secondary School Field',
    'Compassvale Secondary School Hall',
    'Concord Primary School Hall',
    'Damai Secondary School Field',
    'Dazhong Primary School Hall',
    'Deyi Secondary School Field',
    'Deyi Secondary School Hall',
    'Dunman High School Field',
    'Dunman High School Hall',
    'Dunman Secondary School Field',
    'East Spring Primary School Hall',
    'East Spring Secondary School Field',
    'Edgefield Primary School Hall',
    'Edgefield Secondary School Hall',
    'Elias Park Primary School Hall',
    'Enabling Village ActiveSG Gym',
    'Endeavour Primary School Hall',
    'Eunoia Junior College Field - Frisbee only',
    'Eunoia Junior College Sports Hall',
    'Evergreen Primary School Hall',
    'Fajar Secondary School Hall',
    'Farrer Park Tennis Centre',
    'Fengshan Primary School Hall',
    'Fern Green Primary School Hall',
    'First Toa Payoh Primary School Hall',
    'Frontier Primary School Hall',
    'Fuhua Secondary School Field',
    'Fuhua Secondary School Hall',
    'Gan Eng Seng Primary School Hall',
    'Geylang East Swimming Complex',
    'Gongshang Primary School Hall A (Level 3)',
    'Gongshang Primary School Hall B (Level 1)',
    'Greendale Primary School Hall',
    'Greenridge Primary School Hall',
    'Greenridge Secondary School Field',
    'Greenridge Secondary School Hall',
    'Greenwood Primary School Hall',
    'Hai Sing Catholic School Field (Natural grass)',
    "Haig Girls' School Hall",
    'Heartbeat @ Bedok ActiveSG Gym',
    'Heartbeat @ Bedok ActiveSG Sports Hall',
    'Heartbeat @ Bedok ActiveSG Swimming Complex',
    'Heartbeat @ Bedok ActiveSG Tennis Centre',
    'Heartbeat @ Bedok Table Tennis Area',
    'Henry Park Primary School Hall',
    'Hillgrove Secondary School Hall',
    'Hockey Village Hockey 5s Pitch @ Boon Lay',
    'Hockey Village Multi-Purpose Pitch @ Boon Lay',
    'Home of Athletic - Open Artificial Grass Space',
    'Hougang - Between Swimming Pool and Stadium',
    'Hougang ActiveSG Gym',
    'Hougang Primary School Hall',
    'Hougang Secondary School Field',
    'Hougang Secondary School Hall',
    'Hougang Sports Hall',
    'Hougang Stadium Gallery',
    'Hougang Swimming Complex',
    'Hougang Swimming Complex - Table Tennis',
    'Hua Yi Secondary School Field',
    'Hua Yi Secondary School Hall',
    'Huamin Primary School Field',
    'Innova Primary School Hall',
    'Jalan Besar - Main Entance CP Open Space',
    'Jalan Besar ActiveSG Gym',
    'Jalan Besar Swimming Complex',
    'Jiemin Primary School Hall',
    'Junyuan Primary School Hall',
    'Junyuan Secondary School Hall',
    'Jurong East - North Entrance',
    'Jurong East ActiveSG Gym',
    'Jurong East Conference Room',
    'Jurong East Petanque Courts',
    'Jurong East Sports Hall',
    'Jurong East Sports Hall Table Tennis Area',
    'Jurong East Swimming Complex',
    'Jurong Lake Gardens - Pavilion',
    'Jurong Lake Gardens Gym',
    'Jurong Lake Gardens Pool',
    'Jurong Secondary School Hall',
    'Jurong West - Open Space',
    'Jurong West ActiveSG Gym',
    'Jurong West Conference Room',
    'Jurong West Secondary School Field',
    'Jurong West Sport Centre - Table Tennis Area',
    'Jurong West Sports Hall',
    'Jurong West Stadium Gallery',
    'Jurong West Swimming Complex',
    'Jurong West Tennis Centre',
    'Jurong West Training Room',
    'Juying Secondary School Field',
    'Juying Secondary School Hall',
    'Kallang Basin ActiveSG Gym',
    'Kallang Basin Swimming Complex',
    'Kallang Lawn Bowl',
    'Kallang Netball Centre',
    'Kallang Squash Centre',
    'Kallang Tennis Centre',
    'Keming Primary School Hall',
    'Kranji Secondary School Field',
    'Kranji Secondary School Hall',
    'Kuo Chuan Presbyterian Primary School Hall',
    'Kuo Chuan Presbyterian Secondary School Hall',
    'Lakeside Primary School Hall',
    'Lianhua Primary School Hall',
    'Marsiling Primary School Hall',
    'Marsiling Secondary School Field',
    'Mayflower Secondary School Field',
    'Mayflower Secondary School Hall',
    'Meridian Primary School Hall',
    'Meridian Secondary School Field',
    'Meridian Secondary School Hall',
    "Methodist Girls' School Hall (Primary)",
    'Nan Hua High School Field',
    'Nan Hua High School Hall',
    'Nanyang Primary School Hall',
    'Naval Base Secondary School Field',
    'Naval Base Secondary School Hall',
    'New Town Primary School Hall',
    'New Town Secondary School Hall',
    'North Vista Primary School Hall',
    'North Vista Secondary School Field',
    'North Vista Secondary School Hall',
    'Northland Primary School Hall',
    'Northland Secondary School Hall',
    'Northoaks Primary School Hall',
    'Oasis Primary School Hall',
    'Orchid Park Secondary School Field',
    'Our Tampines Hub - Community Auditorium',
    'Our Tampines Hub - Team Sports Hall',
    'Palm View Primary School Hall',
    'Park View Primary School Hall',
    'Pasir ris - Foyer',
    'Pasir Ris 5 a Side Soccer',
    'Pasir Ris ActiveSG Gym',
    'Pasir Ris Crest Secondary School Field',
    'Pasir Ris Crest Secondary School Hall',
    'Pasir Ris Secondary School Field',
    'Pasir Ris Secondary School Hall',
    'Pasir Ris Sports Hall',
    'Pasir Ris Sports Hall Table Tennis Area',
    'Pasir Ris Swimming Complex',
    'Pasir Ris Tennis Centre',
    'Pei Hwa Secondary School Field',
    'Peiying Primary School Hall',
    'Pierce Secondary School Field',
    'Pierce Secondary School Hall',
    'Ping Yi Secondary School Field',
    'Pioneer Primary School Hall (Juying)',
    'Poi Ching School Hall',
    'Princess Elizabeth Primary School Hall',
    'Punggol Green Primary School Hall',
    'Punggol Secondary School Field',
    'Punggol View Primary School Hall',
    'Qifa Primary School Hall',
    'Qihua Primary School Hall',
    'Queenstown Primary School Hall',
    'Queenstown Secondary School Field',
    'Queenstown Stadium Gallery',
    'Queenstown Swimming Complex',
    'Queensway Secondary School Field',
    'Queensway Secondary School Hall',
    'Radin Mas Primary School Hall',
    'Red Swastika School Hall',
    'Regent Secondary School Field',
    'Riverside Secondary School Field',
    'Sembawang Primary School Hall',
    'Seng Kang Primary School Hall',
    'Seng Kang Secondary School Hall',
    'Sengkang - Behind competition pool gallery',
    'Sengkang ActiveSG Gym',
    'Sengkang Conference Room',
    'Sengkang Green Primary School Hall',
    'Sengkang Secondary School Field',
    'SengKang Sport Centre - Open Air Fitness Corner',
    'Sengkang Sport Centre - Table Tennis Area',
    'Sengkang Sports Hall',
    'Sengkang Swimming Complex',
    'Senja Cashew Gym',
    'Senja-Cashew Swimming Complex',
    'Senja-Cashew Tennis Centre',
    'Serangoon - Grass patch Open Space',
    'Serangoon - Open Air Car Park',
    'Serangoon Garden Secondary School Field',
    'Serangoon Garden Secondary School Hall',
    'Serangoon Stadium Gallery',
    'Serangoon Swimming Complex',
    'Serangoon Swimming Complex - Table tennis area',
    'Shuqun Primary School Hall',
    'Silver Circle ActiveSG Gym',
    'Spectra Secondary School Field',
    "St Gabriel's Secondary School Field",
    "St Gabriel's Secondary School Hall",
    "St Patrick's School Hall",
    'St Wilfred Field',
    'St Wilfred Squash Centre',
    'St Wilfred Tennis Centre',
    "St. Anthony's Primary School Hall",
    'Stamford Primary School Hall',
    'Swiss Cottage Secondary School Hall',
    'Tampines ActiveSG Gym',
    'Tampines Swimming Complex',
    'Tanglin Secondary School Field',
    'Tanjong Katong Secondary School Hall',
    'Teck Ghee Primary School Hall',
    'Telok Kurau Primary School Hall',
    'Toa Payoh ActiveSG Gym',
    'Toa Payoh conference Room',
    'Toa Payoh Petanque Courts',
    'Toa Payoh Sports Hall',
    'Toa Payoh Stadium Gallery',
    'Toa Payoh Swimming Complex',
    'Townsville Primary School Hall',
    'Unity Secondary School Field',
    'Unity Secondary School Hall',
    'West Spring Secondary School Hall',
    'West View Primary School Hall',
    'Westwood Secondary School Field',
    'Westwood Secondary School Hall',
    'Woodgrove Primary School Hall',
    'Woodgrove Secondary School Field',
    'Woodgrove Secondary School Hall',
    'Woodlands - Carpark area',
    'Woodlands ActiveSG Gym',
    'Woodlands Ring Primary School Hall',
    'Woodlands Ring Secondary School Field',
    'Woodlands Secondary School Field',
    'Woodlands Secondary School Hall',
    'Woodlands Sports Hall',
    'Woodlands Sports Hall Meeting Room',
    'Woodlands Stadium Gallery',
    'Woodlands Swimming Complex',
    'Xing Hua Primary School',
    'Yio Chu Kang ActiveSG Gym',
    'Yio Chu Kang Conference Room',
    'Yio Chu Kang Primary School Hall',
    'Yio Chu Kang Secondary School Field',
    'Yio Chu Kang Secondary School Hall',
    'Yio Chu Kang Sports Hall',
    'Yio Chu Kang Squash Centre',
    'Yio Chu Kang Stadium Gallery',
    'Yio Chu Kang Swimming Complex',
    'Yio Chu Kang Tennis Centre',
    'Yishun ActiveSG Gym',
    'Yishun Primary School Hall',
    'Yishun Secondary School Hall',
    'Yishun Sports Hall',
    'Yishun Swimming Complex',
    'Yishun Town Secondary School Hall',
    'Yuan Ching Secondary School Field',
    'Yuan Ching Secondary School Hall',
    'Yuying Secondary School Hall',
    'Zhonghua Primary School Hall'
];

export const allSearchOptions = sportsList.concat(venueList).sort((a, b) => a.localeCompare(b));

export const categoryOptionsMap = {
    'Sport': sportsList,
    'Venue': venueList
}